server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/RealEstate-Rental-Project/config-repo-estate-rental.git
          default-label: main
          clone-on-start: true

logging:
  level:
    root: ERROR  # tout ce qui n'est pas explicitement configuré ne log que les erreurs
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    ma.fstt.authserver: DEBUG  # détail des erreurs internes ici
    feign: ERROR


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,refresh
  endpoint:
    prometheus:
      enabled: true
  security:
    enabled: false
