server:
  port: 8888

spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/ahyahya1616/config-repo-estate-rental
          default-label: main
          clone-on-start: true
#eureka:
#  client:
#    register-with-eureka: false
#    fetch-registry: false


logging:
  level:
    root: ERROR  # tout ce qui n'est pas explicitement configuré ne log que les erreurs
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    ma.fstt.authserver: DEBUG  # détail des erreurs internes ici
    feign: ERROR
